name: app_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  dartz: ^0.10.1
  go_router: ^14.0.2
  get_it: ^7.7.0
  logger: ^2.3.0
  dio: ^5.5.0+1
  connectivity_plus: ^6.0.3
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
